# typed: false
# frozen_string_literal: true

# This file was generated by Homebrew. It is not recommended to edit it directly.
# Instead, create a tap repository and place this formula there.

class Quickrag < Formula
  desc "A fast and flexible RAG tool for indexing and querying documents"
  homepage "https://github.com/statico/quickrag"
  url "https://github.com/statico/quickrag/archive/refs/heads/main.tar.gz"
  version "1.0.0"
  license "MIT"
  head "https://github.com/statico/quickrag.git", branch: "main"

  depends_on "bun"

  def install
    # Install dependencies
    system "bun", "install"
    
    # Create a wrapper script that uses bun to run the TypeScript file
    (bin/"quickrag").write <<~EOS
      #!/bin/bash
      exec bun "#{libexec}/src/index.ts" "$@"
    EOS
    
    # Install all source files to libexec
    libexec.install Dir["*"]
    
    # Make the wrapper executable
    chmod 0755, bin/"quickrag"
  end

  def post_install
    # Create config directory if it doesn't exist
    config_dir = "#{Dir.home}/.config/quickrag"
    system "mkdir", "-p", config_dir unless Dir.exist?(config_dir)
  end

  test do
    system "#{bin}/quickrag", "--version"
  end
end
